version: "3.9"

# The containers that compose the project
services:
  # db-test:
  #   image: postgres:13
  #   restart: always
  #   container_name: integration-tests-prisma
  #   ports:
  #     - "5434:5432"
  #   environment:
  #     POSTGRES_USER: prisma
  #     POSTGRES_PASSWORD: prisma
  #     POSTGRES_DB: employee
  db-test:
    image: postgres:13
    # restart: always
    container_name: integration-tests-prisma
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: employee
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      #PGDATA: /var/lib/postgresql/data
    # volumes:
    #   - db-data:/var/lib/postgresql/data
